#######################################
# Openaire Ingest Workflow Config File
#######################################

workflow_config:
  zenodo_url_path: https://zenodo.org/record/8217359 # link to the data dump that you want to download and ingest
  release_date: "20230817" # Has to be in format YYYYMMDD

  # Path to where the data will be stored for the workflow
  working_path: /home/alexmassen-hane/repos/Openaire-Ingest

  # Absolute path of where the secret file for the service account for this workflow to use
  google_secret_path: 

  # List of tables for the workflow to process
  tables:
    communities_infrastructures:
      num_parts: 1

    software:
      num_parts: 1

    relation:
      num_parts: 13

    publication:
      remove_nulls: source # List of columns to go through to remove unnecessary nulls from lists, e.g. "source": ["Crossref",null]
      num_parts: 12

    dataset:
      num_parts: 2

    otherresearchproduct:
      alt_name: otherresearchproduct_1 # Alternative name on Zenodo
      num_parts: 1

    project:
      num_parts: 1

    organization:
      num_parts: 1

    datasource:
      num_parts: 1

cloud_workspace:
  project_id: 
  dataset_id: openaire
  bucket_id: openaire_data
  bucket_folder: "AUG_2023"
  data_location: us